version: '3.8'

services:
  osticket:
    image: osticket/osticket
    restart: always
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: osticket
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: osticket
      OSTICKET_SECRET_KEY: secretkey
      OSTICKET_EMAIL_ADDRESS: osticket@example.com
      OSTICKET_NAME: "osTicket Support System"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

